spring.datasource.url=jdbc:mysql://localhost:3306/fast_food_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root 
spring.datasource.password= 
spring.jpa.hibernate.ddl-auto=update 
server.port=8081 # Đặt cổng khác 8080 để dễ quản lý các service khác sau này