
server:
  port: 8081 # [QUAN TRỌNG] Đổi về 8081 cho khớp với quy hoạch hệ thống (8088 đang trùng Auth Service cũ nếu bạn chưa đổi)

spring:
  application:
    name: customer-service # Tên này sẽ hiện trên Eureka, các service khác sẽ gọi qua tên này
    
  datasource:
    url: jdbc:mysql://localhost:3306/customer_service
    username: root
    password: root  # Dùng mật khẩu MySQL chính xác của bạn
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        
eureka:
  client:
    service-url:
      # Địa chỉ của Eureka Server (8761)
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: true # Đăng ký service này lên Eureka
    fetch-registry: true       # Tải danh sách các service khác về
  instance:
    prefer-ip-address: true    # Quan trọng khi chạy trong Docker để tránh lỗi hostname        