server:
  port: 8080 # Gateway ch·∫°y c·ªïng ch√≠nh 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      # Cho ph√©p request t·ª´ Frontend (CORS)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" # Trong th·ª±c t·∫ø n√™n ƒë·ªÉ domain c·ª• th·ªÉ
            allowedMethods: "*"
            allowedHeaders: "*"

      # C·∫•u h√¨nh c√°c tuy·∫øn ƒë∆∞·ªùng (Routes)
      routes:
        # 1. Auth Service
        - id: auth-service
          uri: lb://AUTH-SERVICE # lb:// nghƒ©a l√† Load Balance qua Eureka
          predicates:
            - Path=/api/auth/**

        # 2. Customer Service
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**

       # 3. Restaurant Service
        - id: restaurant-service
          uri: lb://RESTAURENT-SERVICE    # üëà S·ª≠a l·∫°i gi·ªëng t√™n app
          predicates:
          - Path=/api/v1/restaurants/**


        # 4. Order Service
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**

        # 5. Payment Service
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**

# K·∫øt n·ªëi Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true