server:
  port: 8090 # Đổi sang 8090 vì 8080 là của Gateway

spring:
  application:
    name: auth-service # Tên đăng ký với Eureka

  datasource:
    # Hỗ trợ chạy cả Local và Docker
    url: jdbc:mysql://localhost:3306/auth_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Cấu hình Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# Cấu hình JWT
jwt:
  secret: MySecretKeyForJWT123456789_MustBeVeryLongToSecureHS256Algorithm
  expiration: 86400000 # 1 ngày